### ISSUE TITLE
Support for login without SSH key

### ISSUE THREAD

**Issue by arosen93** [AgnostiqHQ/covalent-slurm-plugin#59]
### What should we add?

I think it would be nice to provide support for just username and password credentials without needing an SSH key. I'd personally never use it, but I'm thinking that it might help for folks who are less programming-inclined and may not be familiar with SSH keys. The downside is that their username and password are then stored as plaintext in the local config, so this shouldn't be done until a system is in place to better handle credential storage.

**Comment by santoshkumarradha** [comment]
This is again a great UX. We initially were considering this even for the first release (I personally always used to SSH with password haha) 

It is crucial to consider more than just storing passwords as plain text. The issue lies in the fact that pickled objects and APIs now include passwords directly, which leaves room for potential interception. In the future, we plan to implement secrets management as a seamless solution. However, if you have any ideas for a somewhat secure way to add user-name and password in the interim, let us start a discussion, very open to it!
